---

- name: Add jsbeautify
  command: wget -O /home/prometeo/.jsbeautifyrc https://raw.githubusercontent.com/Prometeo/dotfiles/master/jsbeautifyrc
  become: false
- name: Configure Emacs
  become: false
  git:
    repo: git@github.com:Prometeo/my_emacs_config.git
    version: master
    dest: "{{ home_path }}/.emacs.d"
    accept_hostkey: yes
