---
# - name: Setting ZSH default shell
#   become: false
#   command: chsh -s /bin/zsh
- name: Create zshrc File
  become: false
  get_url:
    url: https://raw.githubusercontent.com/Prometeo/dotfiles/master/zshrc
    dest: "{{ home_path }}/.zshrc"
- name: Edit tmux conf
  become: false
  lineinfile:
    line: source "/usr/share/tmux/powerline.conf"
    dest: "{{ home_path }}/.tmux"
    create: yes
