---

- name: Clone dotfiles
  become: false
  git:
    repo: https://github.com/Prometeo/dotfiles.git
    version: master
    dest: "{{ home_path }}/dotfiles"
    accept_hostkey: yes
    
- name: Install dotfiles
  command: >-
    ./install
    chdir=/{{ home_path }}/dotfiles
